# Datei: grafana/docker-compose.yml
version: '3'
services:
  grafana:
    image: docbuc/grafana:2
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=geheim
  telegraf:
    image: docbuc/telegraf:2
    build: telegraf/
    restart: always
  influx:
    image: influxdb
    restart: always
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=iijineeZ9iet
      - INFLUXDB_DB=telegraf
